# Generated by Django 3.0.4 on 2020-04-04 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='Name',
            new_name='name',
        ),
    ]
