# Generated by Django 3.0.4 on 2020-04-03 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_art'),
    ]

    operations = [
        migrations.DeleteModel(
            name='art',
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
