# Generated by Django 3.0.4 on 2020-04-03 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_comment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='Commentbox',
        ),
    ]
