# Generated by Django 3.0.4 on 2020-04-03 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_auto_20200402_2308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentbox',
            name='created',
        ),
    ]
